---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: rails-app-deployment
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: rails-app
   template:
     metadata:
       labels:
         app: rails-app
     spec:
       containers:
         - name: rails-web
           image: roshdy/k8s-rails-app
           imagePullPolicy: "Never"
           envFrom:
             - configMapRef:
                 name: rails-config
           ports:
             - containerPort: 8000
