---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: postgres-deployment
 spec:
   selector:
     matchLabels:
       app: postgres
   replicas: 2
   template:
     metadata:
       name: postgres
       labels:
         app: postgres
     spec:
       containers:
         - name: postgres
           image: postgres
           envFrom:
             - configMapRef:
                 name: postgres-config
           volumeMounts:
             - mountPath: /var/lib/postgresql/data
               name: postgresdb
           ports:
             - containerPort: 5432
       volumes:
         - name: postgresdb
           persistentVolumeClaim:
             claimName: postgres-pv-claim
