---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sidekiq-deployment
 spec:
   selector:
     matchLabels:
       app: sidekiq
   replicas: 1
   template:
     metadata:
       name: sidekiq
       labels:
         app: sidekiq
     spec:
       containers:
         - name: rails-sidekiq
           image: roshdy/k8s-rails-app
           imagePullPolicy: "Never"
           envFrom:
             - configMapRef:
                 name: rails-config
           command: ["/bin/sh"]
           args: ["-c", "bundle exec sidekiq"]

